apiVersion: v1
kind: ServiceAccount
metadata:
  name: cbt-client
  namespace: cbt-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cbt-client-cluster-role
rules:
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  - volumesnapshotcontents
  verbs:
  - get
  - list
  - watch
# Access to discover SnapshotMetadataService resources
- apiGroups:
  - cbt.storage.k8s.io
  resources:
  - snapshotmetadataservices
  verbs:
  - get
  - list
# Access to create sa tokens with tokenrequests API
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cbt-client-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cbt-client-cluster-role
subjects:
- kind: ServiceAccount
  name: cbt-client  
  namespace: cbt-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cbt-client
  name: cbt-client
  namespace: cbt-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbt-client
  template:
    metadata:
      labels:
        app: cbt-client
    spec:
      serviceAccountName: cbt-client
      containers:
      - image: prasadg193/external-snapshot-metadata-client:latest
        name: client
        command:
        - sh
        - -c
        - tail -f /dev/null
